window.MPLS_FALLBACK_DATA = {
  "ok": true,
  "mode": "demo",
  "config": {
    "appTitle": "MPLS Quest 38",
    "schoolName": "SMP Negeri 38 Maluku Tengah",
    "teacherName": "Kak Iphoel",
    "tagline": "Kenali Sekolahmu, Temukan Potensimu!",
    "welcome": "Belajar, bermain, berefleksi, dan bertumbuh bersama.",
    "topN": 10,
    "themePrimary": "#4f46e5",
    "themeSecondary": "#06b6d4",
    "themeAccent": "#f59e0b",
    "reflectionBonus": 5,
    "principalName": "LINJIE C. PATTY, S.Pd., M.Si",
    "academicYear": "2025/2026",
    "scheduleLabel": "Semester Genap TP 2025/2026"
  },
  "sessions": [
    {
      "session_id": "DIGI-WED",
      "day_label": "Rabu",
      "title": "Literasi Digital",
      "subtitle": "Cerdas, Aman, dan Seimbang di Dunia Digital",
      "duration_minutes": 60,
      "icon": "🛡️",
      "accent": "cyan",
      "display_order": 1,
      "is_active": true,
      "objectives": "Mengidentifikasi ciri dan modus judi online; memahami dampak negatifnya; mengetahui cara menghindari dan mencari bantuan; menerapkan prinsip 3S: Screen Time, Screen Zone, Screen Break."
    },
    {
      "session_id": "CURR-THU",
      "day_label": "Kamis",
      "title": "Pengenalan Kurikulum",
      "subtitle": "Peta Belajar, Motivasi, dan Strategi Belajar Efektif",
      "duration_minutes": 45,
      "icon": "🧭",
      "accent": "violet",
      "display_order": 2,
      "is_active": true,
      "objectives": "Mengenal struktur kurikulum sekolah; membedakan motivasi intrinsik dan ekstrinsik; mengeksplorasi preferensi dan strategi belajar; membangun kemandirian serta ketangguhan menghadapi tantangan belajar."
    }
  ],
  "content": [
    {
      "content_id": "D-01",
      "session_id": "DIGI-WED",
      "display_order": 1,
      "type": "hero",
      "title": "Misi Literasi Digital",
      "body": "Hari ini kita menjadi Penjaga Dunia Digital. Misi kita bukan sekadar memakai teknologi, tetapi menggunakannya dengan aman, sadar, dan bertanggung jawab.",
      "duration_minutes": 2,
      "icon": "🛡️",
      "accent": "cyan",
      "action": "none",
      "action_label": "",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "D-02",
      "session_id": "DIGI-WED",
      "display_order": 2,
      "type": "objectives",
      "title": "Target Petualangan",
      "body": "• Mengenali ciri dan modus judi online.\n• Menjelaskan dampak terhadap keuangan, keluarga, pertemanan, kesehatan mental, dan masa depan.\n• Menentukan tindakan pencegahan dan sumber bantuan.\n• Menyusun kampanye 3S: Screen Time, Screen Zone, Screen Break.",
      "duration_minutes": 3,
      "icon": "🎯",
      "accent": "blue",
      "action": "none",
      "action_label": "",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "D-03",
      "session_id": "DIGI-WED",
      "display_order": 3,
      "type": "poll",
      "title": "Cek Kebiasaan Digital",
      "body": "Angkat tangan atau pilih jawaban di layar bila pernah:\n• Main gim sampai lupa waktu.\n• Tidur terlalu malam karena gawai.\n• Makan sambil menonton video atau televisi.\n• Belajar sambil membuka terlalu banyak aktivitas.\nTidak ada jawaban untuk mempermalukan siapa pun. Ini hanya titik awal untuk mengenali kebiasaan.",
      "duration_minutes": 3,
      "icon": "📱",
      "accent": "orange",
      "action": "habit_poll",
      "action_label": "Mulai Cek Kebiasaan",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "D-04",
      "session_id": "DIGI-WED",
      "display_order": 4,
      "type": "video",
      "title": "Film Pendek: Kemenangan Sejati",
      "body": "Saksikan film dengan fokus pada tiga hal: cara tokoh mulai terlibat, perubahan yang terjadi, dan keputusan yang seharusnya dapat diambil. Setelah menonton, kita akan berdiskusi tanpa menghakimi tokoh maupun pengalaman orang lain.",
      "duration_minutes": 25,
      "icon": "🎬",
      "accent": "pink",
      "action": "open_media",
      "action_label": "Buka Film",
      "media_url": "https://s.id/antijudol",
      "is_active": true
    },
    {
      "content_id": "D-05",
      "session_id": "DIGI-WED",
      "display_order": 5,
      "type": "discussion",
      "title": "Refleksi Film",
      "body": "Gunakan pertanyaan acak untuk diskusi singkat:\n• Pelajaran paling berharga apa yang kamu peroleh?\n• Mengapa tokoh utama dapat terjerumus?\n• Faktor apa yang mungkin memengaruhinya?\n• Dampak negatif apa yang tampak?\n• Tindakan apa yang akan kamu lakukan dalam situasi serupa?\n• Siapa orang dewasa tepercaya yang dapat dimintai bantuan?",
      "duration_minutes": 5,
      "icon": "💬",
      "accent": "violet",
      "action": "prompt_picker",
      "action_label": "Acak Pertanyaan",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "D-06",
      "session_id": "DIGI-WED",
      "display_order": 6,
      "type": "info",
      "title": "Kenali Pola Risikonya",
      "body": "Tanda bahaya dapat berupa janji keuntungan instan, bonus yang mendesak, ajakan teman, rasa penasaran, dan usaha mengejar kerugian. Dampaknya dapat meluas menjadi kerugian finansial, stres, ketakutan, konflik keluarga, gangguan belajar, dan masalah masa depan. Jangan menyalahkan korban; fokuslah pada keselamatan dan bantuan.",
      "duration_minutes": 3,
      "icon": "⚠️",
      "accent": "red",
      "action": "quiz:digital_core",
      "action_label": "Mainkan Quiz Aman Digital",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "D-07",
      "session_id": "DIGI-WED",
      "display_order": 7,
      "type": "info",
      "title": "Berani Mencari Bantuan",
      "body": "Langkah aman: berhenti dan jangan mengirim uang; simpan bukti seperlunya; blokir akun atau tautan mencurigakan; ceritakan kepada orang tua/wali, guru, wali kelas, guru BK/konselor, atau pihak berwenang; jangan menghadapi tekanan sendirian.",
      "duration_minutes": 2,
      "icon": "🤝",
      "accent": "green",
      "action": "none",
      "action_label": "",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "D-08",
      "session_id": "DIGI-WED",
      "display_order": 8,
      "type": "info",
      "title": "Prinsip 3S",
      "body": "SCREEN TIME — menentukan kapan dan berapa lama menatap layar.\nSCREEN ZONE — menentukan tempat serta situasi yang boleh atau tidak boleh menggunakan gawai.\nSCREEN BREAK — mengambil jeda bermakna untuk bergerak, berinteraksi, beribadah, membaca, berkreasi, atau beristirahat.",
      "duration_minutes": 4,
      "icon": "3S",
      "accent": "cyan",
      "action": "three_s_cards",
      "action_label": "Buka Kartu 3S",
      "media_url": "https://s.id/MateriPrinsip3S",
      "is_active": true
    },
    {
      "content_id": "D-09",
      "session_id": "DIGI-WED",
      "display_order": 9,
      "type": "group_task",
      "title": "Kampanye 3S",
      "body": "Bentuk tiga kelompok. Setiap kelompok mendapat satu misi:\n• Screen Time: poster aturan waktu layar yang realistis.\n• Screen Zone: poster tempat/situasi yang boleh dan tidak boleh untuk memakai gawai.\n• Screen Break: poster kegiatan bermakna selain menatap layar.\nBahan: karton, pensil warna/spidol/crayon, dan perekat.",
      "duration_minutes": 20,
      "icon": "🎨",
      "accent": "orange",
      "action": "three_s_mission",
      "action_label": "Acak Misi Kelompok",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "D-10",
      "session_id": "DIGI-WED",
      "display_order": 10,
      "type": "presentation",
      "title": "Galeri Kampanye",
      "body": "Setiap kelompok mempresentasikan poster secara singkat. Teman lain memberi apresiasi “Satu Kekuatan” dan saran “Satu Langkah Lebih Baik”. Fokus penilaian: pesan jelas, solusi realistis, kreativitas, dan kerja sama.",
      "duration_minutes": 10,
      "icon": "🖼️",
      "accent": "green",
      "action": "rubric",
      "action_label": "Lihat Rubrik",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "D-11",
      "session_id": "DIGI-WED",
      "display_order": 11,
      "type": "reflection",
      "title": "Komitmen Digital Sehat",
      "body": "Tuliskan satu kebiasaan digital yang akan kamu perbaiki, satu aturan 3S yang akan dicoba, dan satu orang dewasa tepercaya yang dapat membantumu.",
      "duration_minutes": 3,
      "icon": "✍️",
      "accent": "violet",
      "action": "reflection",
      "action_label": "Isi Refleksi",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "C-01",
      "session_id": "CURR-THU",
      "display_order": 1,
      "type": "hero",
      "title": "Peta Belajar di SMP",
      "body": "Kurikulum adalah peta perjalanan belajar. Peta ini membantu kita mengetahui apa yang dipelajari, pengalaman apa yang akan dijalani, siapa yang mendampingi, dan bagaimana kita bertumbuh selama berada di SMP.",
      "duration_minutes": 2,
      "icon": "🧭",
      "accent": "violet",
      "action": "none",
      "action_label": "",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "C-02",
      "session_id": "CURR-THU",
      "display_order": 2,
      "type": "info",
      "title": "Kenali Sekolah dan Kepala Sekolah",
      "body": "SMP Negeri 38 Maluku Tengah dipimpin oleh Kepala Sekolah LINJIE C. PATTY, S.Pd., M.Si. Seluruh guru dan tenaga kependidikan bekerja bersama untuk menciptakan pembelajaran yang aman, tertib, menyenangkan, dan membantu setiap murid berkembang.",
      "duration_minutes": 2,
      "icon": "🏫",
      "accent": "blue",
      "action": "school_directory",
      "action_label": "Kenali Warga dan Mata Pelajaran",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "C-03",
      "session_id": "CURR-THU",
      "display_order": 3,
      "type": "info",
      "title": "Mata Pelajaran dan Guru Pengampu",
      "body": "Pada jadwal Semester Genap TP 2025/2026 terdapat Pendidikan Agama dan Budi Pekerti, Pendidikan Pancasila, Bahasa Indonesia, Matematika, IPA, IPS, Bahasa Inggris, Seni dan Prakarya, PJOK, Informatika, Bimbingan Konseling, serta Koding/Muatan Lokal. Buka direktori untuk mengenal guru pengampunya.",
      "duration_minutes": 4,
      "icon": "📚",
      "accent": "cyan",
      "action": "school_directory",
      "action_label": "Buka Direktori Mata Pelajaran",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "C-03Q",
      "session_id": "CURR-THU",
      "display_order": 4,
      "type": "quiz",
      "title": "Quiz Kenal Mata Pelajaran & Guru",
      "body": "Setelah mengenal kepala sekolah, mata pelajaran, dan guru pengampu, uji ingatanmu melalui tantangan cepat. Perhatikan nama mata pelajaran, peran warga sekolah, serta beberapa guru pengampu yang tercantum pada jadwal sekolah.",
      "duration_minutes": 4,
      "icon": "🧠",
      "accent": "violet",
      "action": "quiz:school_directory",
      "action_label": "Mulai Quiz Kenal Mapel & Guru",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "C-04",
      "session_id": "CURR-THU",
      "display_order": 5,
      "type": "info",
      "title": "Wajib, Pilihan, Kokurikuler, dan Ekstrakurikuler",
      "body": "Mata pelajaran wajib membangun kompetensi dasar seluruh murid. Mata pelajaran pilihan—bila tersedia—memberi ruang sesuai minat. Kokurikuler memperkuat pembelajaran melalui pengalaman nyata. Ekstrakurikuler mengembangkan minat, bakat, kepemimpinan, kesehatan, dan kebersamaan. Dalam jadwal sekolah juga terdapat Literasi, Numerasi, Kokurikuler, Pramuka, dan Pembinaan Rohani.",
      "duration_minutes": 2,
      "icon": "🗺️",
      "accent": "green",
      "action": "quiz:curriculum_map",
      "action_label": "Kerjakan Quiz Peta Kurikulum",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "C-05",
      "session_id": "CURR-THU",
      "display_order": 6,
      "type": "info",
      "title": "Dari Mana Semangat Belajar Datang?",
      "body": "Motivasi intrinsik tumbuh dari dalam diri: rasa ingin tahu, minat, makna, atau keinginan berkembang. Motivasi ekstrinsik datang dari luar: nilai, hadiah, pujian, atau kompetisi. Keduanya dapat membantu, tetapi tujuan pribadi yang bermakna membuat semangat lebih tahan lama.",
      "duration_minutes": 4,
      "icon": "🔥",
      "accent": "orange",
      "action": "quiz:motivation",
      "action_label": "Mainkan Detektif Motivasi",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "C-06",
      "session_id": "CURR-THU",
      "display_order": 7,
      "type": "activity",
      "title": "Tujuan Belajar Pribadi",
      "body": "Lengkapi kalimat: “Dalam satu bulan pertama, saya ingin lebih baik dalam … karena … Langkah kecil yang akan saya lakukan adalah …” Tujuan yang baik jelas, realistis, dapat dilakukan, dan dapat ditinjau kembali.",
      "duration_minutes": 6,
      "icon": "🎯",
      "accent": "pink",
      "action": "goal_builder",
      "action_label": "Buat Kartu Tujuan Belajar",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "C-07",
      "session_id": "CURR-THU",
      "display_order": 8,
      "type": "info",
      "title": "Kenali Preferensi Belajarmu",
      "body": "Ada murid yang lebih terbantu dengan mendengar, melihat, membaca, menulis, berdiskusi, atau mencoba langsung. Hasil pertanyaan ini hanya petunjuk awal, bukan label kecerdasan atau batas kemampuan. Strategi terbaik sering menggabungkan beberapa cara.",
      "duration_minutes": 4,
      "icon": "🧠",
      "accent": "violet",
      "action": "preference_quiz",
      "action_label": "Cek Preferensi Belajar",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "C-08",
      "session_id": "CURR-THU",
      "display_order": 9,
      "type": "info",
      "title": "Strategi Belajar Efektif",
      "body": "• Pecah tugas besar menjadi langkah kecil.\n• Tutup buku lalu jelaskan kembali dari ingatan.\n• Ulangi belajar pada waktu berbeda.\n• Buat gambar, contoh, atau hubungan dengan pengalaman nyata.\n• Bertanya pada bagian yang belum dipahami.\n• Atur tempat belajar dan kurangi gangguan.\nPilih strategi berdasarkan tujuan, materi, dan hasil evaluasi.",
      "duration_minutes": 11,
      "icon": "🛠️",
      "accent": "cyan",
      "action": "quiz:study_strategy",
      "action_label": "Tantangan Strategi Belajar",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "C-09",
      "session_id": "CURR-THU",
      "display_order": 10,
      "type": "scenario",
      "title": "Klinik Tantangan Belajar",
      "body": "Kesulitan bukan bukti bahwa kita tidak mampu. Berhenti sejenak, kenali bagian yang sulit, pilih satu langkah, coba strategi lain, minta bantuan, lalu evaluasi hasilnya. Ketangguhan tumbuh melalui latihan, dukungan, dan keberanian mencoba kembali.",
      "duration_minutes": 5,
      "icon": "🧗",
      "accent": "red",
      "action": "quiz:curriculum_challenge",
      "action_label": "Pecahkan Skenario Belajar",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "C-10",
      "session_id": "CURR-THU",
      "display_order": 11,
      "type": "reflection",
      "title": "Refleksi 3M + 1L",
      "body": "MENGERTI — Apa yang sudah saya pahami?\nMENGGANJAL — Apa yang masih membingungkan atau belum saya kuasai?\nMENARIK — Bagian mana yang paling menarik atau paling sulit?\nLANGKAH — Apa rencana kecil saya selanjutnya?",
      "duration_minutes": 4,
      "icon": "🪞",
      "accent": "green",
      "action": "reflection",
      "action_label": "Isi Refleksi 3M + 1L",
      "media_url": "",
      "is_active": true
    },
    {
      "content_id": "C-11",
      "session_id": "CURR-THU",
      "display_order": 12,
      "type": "closing",
      "title": "Saya Siap Menjadi Pelajar Tangguh",
      "body": "Kamu tidak harus langsung mahir. Kenali tujuanmu, pilih strategi yang sesuai, minta bantuan ketika perlu, dan terus perbaiki langkah. Keberhasilan belajar dibangun sedikit demi sedikit melalui kebiasaan yang dilakukan secara konsisten.",
      "duration_minutes": 1,
      "icon": "🌟",
      "accent": "orange",
      "action": "curriculum_closing",
      "action_label": "Baca Komitmen Pelajar",
      "media_url": "",
      "is_active": true
    }
  ],
  "questions": [
    {
      "question_id": "DQ-01",
      "session_id": "DIGI-WED",
      "category": "digital_core",
      "question_type": "multiple_choice",
      "prompt": "Ajakan mana yang merupakan tanda bahaya paling jelas?",
      "option_a": "Belajar membuat poster bersama",
      "option_b": "Bonus besar dijanjikan bila segera mengirim uang",
      "option_c": "Mengatur waktu layar bersama keluarga",
      "option_d": "Beristirahat setelah belajar",
      "correct_answer": "B",
      "explanation": "Janji keuntungan atau bonus instan yang mendesak adalah tanda bahaya. Jangan mengirim uang atau data pribadi.",
      "points": 10,
      "time_limit_sec": 20,
      "display_order": 1,
      "is_active": true
    },
    {
      "question_id": "DQ-02",
      "session_id": "DIGI-WED",
      "category": "digital_core",
      "question_type": "multiple_choice",
      "prompt": "Mengapa seseorang dapat terjerumus dalam judi online?",
      "option_a": "Hanya karena tidak pandai belajar",
      "option_b": "Hanya karena memakai telepon",
      "option_c": "Gabungan rasa penasaran, tekanan teman, janji untung instan, atau masalah ekonomi",
      "option_d": "Karena semua permainan digital adalah judi",
      "correct_answer": "C",
      "explanation": "Risiko dapat dipengaruhi banyak faktor. Memahami faktor membantu pencegahan tanpa menyalahkan korban.",
      "points": 10,
      "time_limit_sec": 25,
      "display_order": 2,
      "is_active": true
    },
    {
      "question_id": "DQ-03",
      "session_id": "DIGI-WED",
      "category": "digital_core",
      "question_type": "multiple_choice",
      "prompt": "Dampak judi online dapat memengaruhi ...",
      "option_a": "Keuangan saja",
      "option_b": "Kesehatan mental saja",
      "option_c": "Pertemanan saja",
      "option_d": "Keuangan, hubungan, kesehatan mental, belajar, dan masa depan",
      "correct_answer": "D",
      "explanation": "Dampaknya dapat meluas ke berbagai bagian kehidupan.",
      "points": 10,
      "time_limit_sec": 20,
      "display_order": 3,
      "is_active": true
    },
    {
      "question_id": "DQ-04",
      "session_id": "DIGI-WED",
      "category": "digital_core",
      "question_type": "multiple_choice",
      "prompt": "Apa tindakan paling aman ketika mendapat tautan permainan berhadiah yang mencurigakan?",
      "option_a": "Mencoba sekali agar tahu",
      "option_b": "Meneruskan ke teman",
      "option_c": "Tidak membuka, memblokir, dan menceritakannya kepada orang dewasa tepercaya",
      "option_d": "Mengirim data palsu",
      "correct_answer": "C",
      "explanation": "Jangan berinteraksi dengan tautan mencurigakan. Cari bantuan dari orang dewasa tepercaya.",
      "points": 10,
      "time_limit_sec": 20,
      "display_order": 4,
      "is_active": true
    },
    {
      "question_id": "DQ-05",
      "session_id": "DIGI-WED",
      "category": "digital_core",
      "question_type": "multiple_choice",
      "prompt": "Manakah contoh Screen Time?",
      "option_a": "Menentukan maksimal waktu bermain gim setelah tugas selesai",
      "option_b": "Tidak memakai gawai di tempat ibadah",
      "option_c": "Berjalan kaki selama jeda layar",
      "option_d": "Menyimpan gawai di tas saat diskusi",
      "correct_answer": "A",
      "explanation": "Screen Time berhubungan dengan kapan dan berapa lama layar digunakan.",
      "points": 10,
      "time_limit_sec": 15,
      "display_order": 5,
      "is_active": true
    },
    {
      "question_id": "DQ-06",
      "session_id": "DIGI-WED",
      "category": "digital_core",
      "question_type": "multiple_choice",
      "prompt": "Manakah contoh Screen Zone?",
      "option_a": "Istirahat mata setiap 20 menit",
      "option_b": "Kesepakatan tidak menggunakan gawai saat makan bersama",
      "option_c": "Membatasi gim selama 30 menit",
      "option_d": "Tidur lebih awal",
      "correct_answer": "B",
      "explanation": "Screen Zone menetapkan tempat atau situasi penggunaan gawai.",
      "points": 10,
      "time_limit_sec": 15,
      "display_order": 6,
      "is_active": true
    },
    {
      "question_id": "DQ-07",
      "session_id": "DIGI-WED",
      "category": "digital_core",
      "question_type": "multiple_choice",
      "prompt": "Manakah contoh Screen Break yang bermakna?",
      "option_a": "Berpindah dari gim ke video pendek",
      "option_b": "Membuka media sosial lain",
      "option_c": "Berjalan, berbicara dengan keluarga, atau membuat karya tanpa layar",
      "option_d": "Mengurangi terang layar sambil terus bermain",
      "correct_answer": "C",
      "explanation": "Screen Break berarti benar-benar mengambil jeda dari layar untuk kegiatan lain yang sehat dan bermakna.",
      "points": 10,
      "time_limit_sec": 15,
      "display_order": 7,
      "is_active": true
    },
    {
      "question_id": "DQ-08",
      "session_id": "DIGI-WED",
      "category": "digital_core",
      "question_type": "multiple_choice",
      "prompt": "Siapa yang dapat dimintai bantuan ketika menghadapi tekanan atau masalah judi online?",
      "option_a": "Orang tua/wali, guru, wali kelas, guru BK/konselor, atau pihak berwenang",
      "option_b": "Akun anonim yang menawarkan pinjaman",
      "option_c": "Orang yang mengajak bermain",
      "option_d": "Tidak perlu siapa pun",
      "correct_answer": "A",
      "explanation": "Masalah ini tidak perlu dihadapi sendirian. Pilih orang dewasa yang tepercaya dan aman.",
      "points": 10,
      "time_limit_sec": 20,
      "display_order": 8,
      "is_active": true
    },
    {
      "question_id": "CQ-01",
      "session_id": "CURR-THU",
      "category": "curriculum_map",
      "question_type": "multiple_choice",
      "prompt": "Kurikulum paling tepat dipahami sebagai ...",
      "option_a": "Daftar hukuman dan ujian saja",
      "option_b": "Peta yang mengarahkan tujuan, isi, pengalaman, dan kegiatan belajar",
      "option_c": "Jadwal olahraga saja",
      "option_d": "Daftar nama guru saja",
      "correct_answer": "B",
      "explanation": "Kurikulum menjadi peta yang mengarahkan tujuan, isi, pengalaman, dan kegiatan pengembangan murid.",
      "points": 10,
      "time_limit_sec": 20,
      "display_order": 1,
      "is_active": true
    },
    {
      "question_id": "CQ-02",
      "session_id": "CURR-THU",
      "category": "curriculum_map",
      "question_type": "multiple_choice",
      "prompt": "Kegiatan Literasi, Numerasi, Kokurikuler, Pramuka, dan Pembinaan Rohani membantu murid untuk ...",
      "option_a": "Mengganti seluruh mata pelajaran",
      "option_b": "Memperkuat pengalaman belajar dan pengembangan diri",
      "option_c": "Mengurangi kesempatan belajar",
      "option_d": "Menentukan siapa yang paling populer",
      "correct_answer": "B",
      "explanation": "Kegiatan tersebut memperkuat pengalaman belajar, karakter, minat, keterampilan, dan kebersamaan.",
      "points": 10,
      "time_limit_sec": 20,
      "display_order": 2,
      "is_active": true
    },
    {
      "question_id": "CM-01",
      "session_id": "CURR-THU",
      "category": "motivation",
      "question_type": "multiple_choice",
      "prompt": "Dina belajar bahasa karena tertarik dengan budaya dan film negara tersebut. Motivasinya terutama ...",
      "option_a": "Intrinsik",
      "option_b": "Ekstrinsik",
      "option_c": "Tidak ada motivasi",
      "option_d": "Hanya kebiasaan",
      "correct_answer": "A",
      "explanation": "Ketertarikan dan rasa ingin tahu berasal dari dalam diri.",
      "points": 10,
      "time_limit_sec": 20,
      "display_order": 1,
      "is_active": true
    },
    {
      "question_id": "CM-02",
      "session_id": "CURR-THU",
      "category": "motivation",
      "question_type": "multiple_choice",
      "prompt": "Raka berlatih keras agar memperoleh hadiah lomba. Motivasinya terutama ...",
      "option_a": "Intrinsik",
      "option_b": "Ekstrinsik",
      "option_c": "Tidak relevan",
      "option_d": "Tidak dapat berubah",
      "correct_answer": "B",
      "explanation": "Hadiah merupakan pendorong dari luar. Motivasi ekstrinsik dapat membantu, tetapi dapat diperkuat dengan tujuan pribadi yang bermakna.",
      "points": 10,
      "time_limit_sec": 20,
      "display_order": 2,
      "is_active": true
    },
    {
      "question_id": "CM-03",
      "session_id": "CURR-THU",
      "category": "motivation",
      "question_type": "multiple_choice",
      "prompt": "Pernyataan tujuan belajar yang paling jelas dan realistis adalah ...",
      "option_a": "Saya harus sempurna dalam semua hal",
      "option_b": "Saya akan lebih rajin suatu saat nanti",
      "option_c": "Selama dua minggu saya berlatih lima soal matematika setiap sore dan mencatat bagian yang sulit",
      "option_d": "Saya ingin nilai tinggi tanpa mengubah kebiasaan",
      "correct_answer": "C",
      "explanation": "Tujuan yang jelas menyebut tindakan, waktu, dan cara memantau kemajuan.",
      "points": 10,
      "time_limit_sec": 25,
      "display_order": 3,
      "is_active": true
    },
    {
      "question_id": "CP-01",
      "session_id": "CURR-THU",
      "category": "preference",
      "question_type": "preference",
      "prompt": "Saat mempelajari sesuatu yang baru, apa yang paling membantu kamu memahami?",
      "option_a": "Mendengar penjelasan dari guru atau teman",
      "option_b": "Melihat gambar, diagram, video, atau membaca teks",
      "option_c": "Mencoba langsung, melakukan eksperimen, atau berpartisipasi aktif",
      "option_d": "",
      "correct_answer": "",
      "explanation": "",
      "points": 0,
      "time_limit_sec": 0,
      "display_order": 1,
      "is_active": true
    },
    {
      "question_id": "CP-02",
      "session_id": "CURR-THU",
      "category": "preference",
      "question_type": "preference",
      "prompt": "Saat membaca buku atau materi, apa yang biasanya kamu lakukan untuk memahami isinya?",
      "option_a": "Membaca dengan suara pelan atau bergumam",
      "option_b": "Melihat poin penting atau ilustrasi",
      "option_c": "Membuat catatan dengan tangan atau menandai buku",
      "option_d": "",
      "correct_answer": "",
      "explanation": "",
      "points": 0,
      "time_limit_sec": 0,
      "display_order": 2,
      "is_active": true
    },
    {
      "question_id": "CP-03",
      "session_id": "CURR-THU",
      "category": "preference",
      "question_type": "preference",
      "prompt": "Bagaimana kamu biasanya mempelajari arah atau rute baru?",
      "option_a": "Mendengar instruksi lisan",
      "option_b": "Melihat peta atau petunjuk tertulis",
      "option_c": "Berjalan langsung melalui rute tersebut",
      "option_d": "",
      "correct_answer": "",
      "explanation": "",
      "points": 0,
      "time_limit_sec": 0,
      "display_order": 3,
      "is_active": true
    },
    {
      "question_id": "CS-01",
      "session_id": "CURR-THU",
      "category": "study_strategy",
      "question_type": "multiple_choice",
      "prompt": "Setelah membaca satu halaman, strategi yang membantu memeriksa pemahaman adalah ...",
      "option_a": "Membaca ulang tanpa berhenti berkali-kali",
      "option_b": "Menutup buku lalu menjelaskan inti dari ingatan",
      "option_c": "Membuka banyak aplikasi sekaligus",
      "option_d": "Menunggu sampai sehari sebelum ujian",
      "correct_answer": "B",
      "explanation": "Mencoba mengambil kembali informasi dari ingatan membantu mengetahui apa yang sudah dan belum dipahami.",
      "points": 10,
      "time_limit_sec": 20,
      "display_order": 1,
      "is_active": true
    },
    {
      "question_id": "CS-02",
      "session_id": "CURR-THU",
      "category": "study_strategy",
      "question_type": "multiple_choice",
      "prompt": "Tugas terasa terlalu besar. Langkah awal yang paling efektif adalah ...",
      "option_a": "Menghindarinya",
      "option_b": "Membandingkan diri dengan teman",
      "option_c": "Memecah tugas menjadi beberapa langkah kecil dan menentukan langkah pertama",
      "option_d": "Mengerjakan semuanya sekaligus tanpa rencana",
      "correct_answer": "C",
      "explanation": "Langkah kecil membuat tugas lebih terkelola dan memudahkan kita memulai.",
      "points": 10,
      "time_limit_sec": 20,
      "display_order": 2,
      "is_active": true
    },
    {
      "question_id": "CS-03",
      "session_id": "CURR-THU",
      "category": "study_strategy",
      "question_type": "multiple_choice",
      "prompt": "Cara terbaik memilih strategi belajar adalah ...",
      "option_a": "Menggunakan satu cara untuk semua materi selamanya",
      "option_b": "Menyesuaikan strategi dengan tujuan, materi, dan hasil evaluasi",
      "option_c": "Mengikuti cara teman tanpa mencoba",
      "option_d": "Memilih cara yang paling cepat walau tidak memahami",
      "correct_answer": "B",
      "explanation": "Strategi belajar perlu fleksibel. Gabungkan mendengar, melihat, menulis, berdiskusi, dan praktik sesuai kebutuhan.",
      "points": 10,
      "time_limit_sec": 20,
      "display_order": 3,
      "is_active": true
    },
    {
      "question_id": "CC-01",
      "session_id": "CURR-THU",
      "category": "curriculum_challenge",
      "question_type": "multiple_choice",
      "prompt": "Kamu belum memahami materi meskipun sudah mencoba. Tindakan berikutnya yang paling tepat adalah ...",
      "option_a": "Menyimpulkan bahwa kamu tidak mampu",
      "option_b": "Mengenali bagian yang sulit, mencoba strategi lain, dan meminta bantuan",
      "option_c": "Menyalin jawaban tanpa memahami",
      "option_d": "Berhenti belajar selamanya",
      "correct_answer": "B",
      "explanation": "Ketangguhan berarti menilai masalah, mencoba langkah baru, dan menggunakan dukungan yang tersedia.",
      "points": 10,
      "time_limit_sec": 25,
      "display_order": 1,
      "is_active": true
    },
    {
      "question_id": "CC-02",
      "session_id": "CURR-THU",
      "category": "curriculum_challenge",
      "question_type": "multiple_choice",
      "prompt": "Refleksi belajar yang paling membantu adalah ...",
      "option_a": "“Semuanya sulit.”",
      "option_b": "“Saya gagal.”",
      "option_c": "“Saya memahami bagian A, masih bingung pada B, dan besok akan mencoba latihan serta bertanya.”",
      "option_d": "“Tidak perlu menilai cara belajar.”",
      "correct_answer": "C",
      "explanation": "Refleksi yang baik menyebut bukti, kesulitan, dan rencana langkah berikutnya.",
      "points": 10,
      "time_limit_sec": 25,
      "display_order": 2,
      "is_active": true
    },
    {
      "question_id": "CQ-03",
      "session_id": "CURR-THU",
      "category": "curriculum_map",
      "question_type": "multiple_choice",
      "prompt": "Siapa Kepala Sekolah SMP Negeri 38 Maluku Tengah yang diperkenalkan pada materi ini?",
      "option_a": "LINJIE C. PATTY, S.Pd., M.Si",
      "option_b": "Kak Iphoel",
      "option_c": "Ketua kelas",
      "option_d": "Ketua OSIS",
      "correct_answer": "A",
      "explanation": "Kepala Sekolah SMP Negeri 38 Maluku Tengah adalah LINJIE C. PATTY, S.Pd., M.Si.",
      "points": 10,
      "time_limit_sec": 20,
      "display_order": 3,
      "is_active": true
    },
    {
      "question_id": "CDQ-01",
      "session_id": "CURR-THU",
      "category": "school_directory",
      "question_type": "multiple_choice",
      "prompt": "Mata pelajaran yang melatih pemahaman bilangan, pola, bentuk, dan pemecahan masalah adalah ...",
      "option_a": "Matematika",
      "option_b": "PJOK",
      "option_c": "Seni dan Prakarya",
      "option_d": "Bimbingan Konseling",
      "correct_answer": "A",
      "explanation": "Matematika membantu murid memahami bilangan, pola, bentuk, hubungan, penalaran, dan pemecahan masalah.",
      "points": 10,
      "time_limit_sec": 20,
      "display_order": 1,
      "is_active": true
    },
    {
      "question_id": "CDQ-02",
      "session_id": "CURR-THU",
      "category": "school_directory",
      "question_type": "multiple_choice",
      "prompt": "N.N. Souisa tercantum pada direktori sekolah sebagai salah satu guru pengampu mata pelajaran ...",
      "option_a": "IPS",
      "option_b": "Informatika",
      "option_c": "PJOK",
      "option_d": "Bahasa Inggris",
      "correct_answer": "B",
      "explanation": "Pada jadwal yang menjadi referensi aplikasi, N.N. Souisa tercantum sebagai salah satu guru pengampu Informatika untuk jenjang VII.",
      "points": 10,
      "time_limit_sec": 20,
      "display_order": 2,
      "is_active": true
    },
    {
      "question_id": "CDQ-03",
      "session_id": "CURR-THU",
      "category": "school_directory",
      "question_type": "multiple_choice",
      "prompt": "S. Kurniawan, S.Pd tercantum sebagai guru pengampu Koding/Muatan Lokal untuk jenjang ...",
      "option_a": "VII",
      "option_b": "VIII",
      "option_c": "IX",
      "option_d": "Semua jenjang",
      "correct_answer": "A",
      "explanation": "Pada jadwal Semester Genap TP 2025/2026, S. Kurniawan, S.Pd tercantum mengampu Koding/Muatan Lokal pada jenjang VII.",
      "points": 10,
      "time_limit_sec": 20,
      "display_order": 3,
      "is_active": true
    },
    {
      "question_id": "CDQ-04",
      "session_id": "CURR-THU",
      "category": "school_directory",
      "question_type": "multiple_choice",
      "prompt": "LINJIE C. PATTY, S.Pd., M.Si diperkenalkan dalam materi sebagai ...",
      "option_a": "Ketua OSIS",
      "option_b": "Wali kelas",
      "option_c": "Kepala SMP Negeri 38 Maluku Tengah",
      "option_d": "Ketua kelompok belajar",
      "correct_answer": "C",
      "explanation": "LINJIE C. PATTY, S.Pd., M.Si diperkenalkan sebagai Kepala SMP Negeri 38 Maluku Tengah.",
      "points": 10,
      "time_limit_sec": 20,
      "display_order": 4,
      "is_active": true
    },
    {
      "question_id": "CDQ-05",
      "session_id": "CURR-THU",
      "category": "school_directory",
      "question_type": "multiple_choice",
      "prompt": "Data guru pengampu yang tampil pada direktori aplikasi ini diambil dari ...",
      "option_a": "Daftar tebakan siswa",
      "option_b": "Jadwal Semester Genap TP 2025/2026",
      "option_c": "Hasil permainan kelas",
      "option_d": "Daftar sekolah lain",
      "correct_answer": "B",
      "explanation": "Direktori mata pelajaran dan guru pengampu disusun dari Jadwal Semester Genap TP 2025/2026 yang diberikan sekolah dan perlu diperiksa kembali apabila ada pembagian tugas terbaru.",
      "points": 10,
      "time_limit_sec": 20,
      "display_order": 5,
      "is_active": true
    }
  ],
  "activities": [
    {
      "activity_id": "DA-01",
      "session_id": "DIGI-WED",
      "title": "Nonton Bersama Film Pencegahan Judi Online",
      "description": "Saksikan film Kemenangan Sejati dan catat pola risiko, dampak, serta keputusan aman.",
      "duration_minutes": 25,
      "materials": "Laptop, proyektor, pengeras suara, tautan film",
      "group_mode": "kelas",
      "rubric": "Fokus; kemampuan mengidentifikasi pola; sikap tidak menghakimi",
      "display_order": 1,
      "is_active": true
    },
    {
      "activity_id": "DA-02",
      "session_id": "DIGI-WED",
      "title": "Diskusi dan Refleksi Film",
      "description": "Diskusi singkat menggunakan pertanyaan reflektif dan pesan bantuan.",
      "duration_minutes": 5,
      "materials": "Kertas dan alat tulis",
      "group_mode": "kelas",
      "rubric": "Relevansi alasan; empati; solusi aman",
      "display_order": 2,
      "is_active": true
    },
    {
      "activity_id": "DA-03",
      "session_id": "DIGI-WED",
      "title": "Kampanye 3S",
      "description": "Tiga kelompok membuat poster Screen Time, Screen Zone, atau Screen Break.",
      "duration_minutes": 30,
      "materials": "Karton, alat warna, perekat",
      "group_mode": "3 kelompok",
      "rubric": "Pesan jelas 30%; solusi realistis 25%; kreativitas 20%; kerja sama 25%",
      "display_order": 3,
      "is_active": true
    },
    {
      "activity_id": "CA-01",
      "session_id": "CURR-THU",
      "title": "Mengenal Mata Pelajaran, Guru Pengampu, dan Kegiatan Sekolah",
      "description": "Mengenal struktur kurikulum, kepala sekolah, mata pelajaran, guru pengampu, serta kegiatan kokurikuler dan ekstrakurikuler.",
      "duration_minutes": 10,
      "materials": "Proyektor dan informasi jadwal resmi sekolah",
      "group_mode": "kelas",
      "rubric": "Ketepatan pemahaman; keberanian bertanya; sikap menghargai warga sekolah",
      "display_order": 1,
      "is_active": true
    },
    {
      "activity_id": "CA-02",
      "session_id": "CURR-THU",
      "title": "Mengenal Diri dan Membangkitkan Motivasi",
      "description": "Membedakan motivasi intrinsik dan ekstrinsik serta menyusun tujuan belajar pribadi yang jelas dan realistis.",
      "duration_minutes": 10,
      "materials": "Kertas atau HP siswa dan alat tulis",
      "group_mode": "individu/kelas",
      "rubric": "Alasan bermakna; tujuan jelas; langkah realistis",
      "display_order": 2,
      "is_active": true
    },
    {
      "activity_id": "CA-03",
      "session_id": "CURR-THU",
      "title": "Teknik dan Strategi Belajar Efektif",
      "description": "Mengenali preferensi belajar sebagai petunjuk awal dan mencoba strategi belajar yang sesuai dengan tujuan dan materi.",
      "duration_minutes": 15,
      "materials": "HP siswa/kertas dan alat tulis",
      "group_mode": "individu/kelas",
      "rubric": "Kesadaran diri; fleksibilitas strategi; partisipasi",
      "display_order": 3,
      "is_active": true
    },
    {
      "activity_id": "CA-04",
      "session_id": "CURR-THU",
      "title": "Mengatasi Tantangan Belajar dan Refleksi",
      "description": "Menganalisis kesulitan belajar, memilih solusi, melakukan refleksi 3M+1L, dan menyusun langkah berikutnya.",
      "duration_minutes": 10,
      "materials": "HP siswa/kertas dan alat tulis",
      "group_mode": "individu/kelas",
      "rubric": "Analisis masalah; solusi; tanggung jawab; refleksi",
      "display_order": 4,
      "is_active": true
    }
  ],
  "reflectionPrompts": {
    "DIGI-WED": [
      "Pelajaran paling penting yang saya dapat hari ini adalah ...",
      "Satu kebiasaan digital yang akan saya perbaiki adalah ...",
      "Aturan 3S yang akan saya coba adalah ...",
      "Orang dewasa tepercaya yang dapat saya hubungi adalah ..."
    ],
    "CURR-THU": [
      "MENGERTI — Apa yang sudah saya pelajari dan pahami dengan baik?",
      "MENGGANJAL — Apa yang masih membingungkan atau belum saya kuasai?",
      "MENARIK — Bagian mana yang paling menarik atau paling sulit?",
      "LANGKAH — Apa satu rencana kecil yang akan saya lakukan selanjutnya?"
    ]
  },
  "leaderboard": [],
  "schoolDirectory": [
    {
      "directory_id": "HEADMASTER-01",
      "kind": "principal",
      "subject_code": "",
      "subject_name": "",
      "person_name": "LINJIE C. PATTY, S.Pd., M.Si",
      "role": "Kepala Sekolah",
      "grade_levels": "",
      "classes": "",
      "icon": "🏫",
      "display_order": 1,
      "is_active": true
    },
    {
      "directory_id": "SUB-A-08",
      "kind": "subject_teacher",
      "subject_code": "A",
      "subject_name": "Pendidikan Agama dan Budi Pekerti",
      "person_name": "C. Hatalabessy, S.Th.,M.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "IX",
      "classes": "IX Bilingual, IX Sains, IX Seni, IX-1, IX-2, IX-3, IX-5",
      "icon": "🕌",
      "display_order": 10,
      "is_active": true
    },
    {
      "directory_id": "SUB-A-10",
      "kind": "subject_teacher",
      "subject_code": "A",
      "subject_name": "Pendidikan Agama dan Budi Pekerti",
      "person_name": "Hasanudin, S.PdI",
      "role": "Guru Pengampu",
      "grade_levels": "IX",
      "classes": "IX Bilingual, IX Sains, IX Seni, IX-1, IX-2, IX-3, IX-5",
      "icon": "🕌",
      "display_order": 10,
      "is_active": true
    },
    {
      "directory_id": "SUB-A-11",
      "kind": "subject_teacher",
      "subject_code": "A",
      "subject_name": "Pendidikan Agama dan Budi Pekerti",
      "person_name": "R. Fid, S.Ag",
      "role": "Guru Pengampu",
      "grade_levels": "VIII",
      "classes": "VIII Bilingual, VIII Sains, VIII Seni, VIII-1, VIII-2, VIII-3, VIII-4, VIII-5",
      "icon": "🕌",
      "display_order": 10,
      "is_active": true
    },
    {
      "directory_id": "SUB-A-15",
      "kind": "subject_teacher",
      "subject_code": "A",
      "subject_name": "Pendidikan Agama dan Budi Pekerti",
      "person_name": "S. Suryani, S.PdI",
      "role": "Guru Pengampu",
      "grade_levels": "VII",
      "classes": "VII Bilingual, VII Sains, VII Seni, VII-1, VII-2, VII-3, VII-4, VII-5",
      "icon": "🕌",
      "display_order": 10,
      "is_active": true
    },
    {
      "directory_id": "SUB-A-17",
      "kind": "subject_teacher",
      "subject_code": "A",
      "subject_name": "Pendidikan Agama dan Budi Pekerti",
      "person_name": "H. Efruan, S.Th",
      "role": "Guru Pengampu",
      "grade_levels": "VII",
      "classes": "VII Bilingual, VII Sains, VII Seni, VII-1, VII-2, VII-3, VII-4, VII-5",
      "icon": "🕌",
      "display_order": 10,
      "is_active": true
    },
    {
      "directory_id": "SUB-A-30",
      "kind": "subject_teacher",
      "subject_code": "A",
      "subject_name": "Pendidikan Agama dan Budi Pekerti",
      "person_name": "K. Waeleuruw, S.Th",
      "role": "Guru Pengampu",
      "grade_levels": "VIII",
      "classes": "VIII Bilingual, VIII Sains, VIII Seni, VIII-1, VIII-2, VIII-3, VIII-4, VIII-5",
      "icon": "🕌",
      "display_order": 10,
      "is_active": true
    },
    {
      "directory_id": "SUB-B-18",
      "kind": "subject_teacher",
      "subject_code": "B",
      "subject_name": "Pendidikan Pancasila",
      "person_name": "P. Ruspanah, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII, IX",
      "classes": "IX Bilingual, IX-2, IX-3, IX-4, VII Sains, VII Seni, VII-1, VII-2",
      "icon": "🇮🇩",
      "display_order": 20,
      "is_active": true
    },
    {
      "directory_id": "SUB-B-28",
      "kind": "subject_teacher",
      "subject_code": "B",
      "subject_name": "Pendidikan Pancasila",
      "person_name": "S. Leapary, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VIII",
      "classes": "VIII Bilingual, VIII Sains, VIII Seni, VIII-1, VIII-2, VIII-3, VIII-4, VIII-5",
      "icon": "🇮🇩",
      "display_order": 20,
      "is_active": true
    },
    {
      "directory_id": "SUB-B-38",
      "kind": "subject_teacher",
      "subject_code": "B",
      "subject_name": "Pendidikan Pancasila",
      "person_name": "N.Tuamain,S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII, IX",
      "classes": "IX Sains, IX Seni, IX-1, IX-5, VII Bilingual, VII-3, VII-4, VII-5",
      "icon": "🇮🇩",
      "display_order": 20,
      "is_active": true
    },
    {
      "directory_id": "SUB-C-09",
      "kind": "subject_teacher",
      "subject_code": "C",
      "subject_name": "Bahasa Indonesia",
      "person_name": "S.I. Limamuly, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "IX",
      "classes": "IX Sains, IX-2, IX-3, IX-4",
      "icon": "📖",
      "display_order": 30,
      "is_active": true
    },
    {
      "directory_id": "SUB-C-13",
      "kind": "subject_teacher",
      "subject_code": "C",
      "subject_name": "Bahasa Indonesia",
      "person_name": "Nunung Yuliani, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VIII",
      "classes": "VIII Bilingual, VIII-1, VIII-3, VIII-5",
      "icon": "📖",
      "display_order": 30,
      "is_active": true
    },
    {
      "directory_id": "SUB-C-14",
      "kind": "subject_teacher",
      "subject_code": "C",
      "subject_name": "Bahasa Indonesia",
      "person_name": "Y. Silawane, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "IX",
      "classes": "IX Bilingual, IX Seni, IX-1, IX-5",
      "icon": "📖",
      "display_order": 30,
      "is_active": true
    },
    {
      "directory_id": "SUB-C-20",
      "kind": "subject_teacher",
      "subject_code": "C",
      "subject_name": "Bahasa Indonesia",
      "person_name": "W.Wattimena, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII",
      "classes": "VII Bilingual, VII Sains, VII Seni, VII-4",
      "icon": "📖",
      "display_order": 30,
      "is_active": true
    },
    {
      "directory_id": "SUB-C-36",
      "kind": "subject_teacher",
      "subject_code": "C",
      "subject_name": "Bahasa Indonesia",
      "person_name": "J.G.Payong, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII",
      "classes": "VII-1, VII-2, VII-3, VII-5",
      "icon": "📖",
      "display_order": 30,
      "is_active": true
    },
    {
      "directory_id": "SUB-C-37",
      "kind": "subject_teacher",
      "subject_code": "C",
      "subject_name": "Bahasa Indonesia",
      "person_name": "M.Matulessy, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VIII",
      "classes": "VIII Sains, VIII Seni, VIII-2, VIII-4",
      "icon": "📖",
      "display_order": 30,
      "is_active": true
    },
    {
      "directory_id": "SUB-D-25",
      "kind": "subject_teacher",
      "subject_code": "D",
      "subject_name": "Matematika",
      "person_name": "S.Tomu, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII, IX",
      "classes": "IX Sains, IX-1, IX-2, VII-2, VII-3, VII-4",
      "icon": "➗",
      "display_order": 40,
      "is_active": true
    },
    {
      "directory_id": "SUB-D-33",
      "kind": "subject_teacher",
      "subject_code": "D",
      "subject_name": "Matematika",
      "person_name": "M. Komul, S.Pd.,M.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII, VIII, IX",
      "classes": "IX Bilingual, IX Seni, IX-5, VII Sains, VII-1, VIII Sains",
      "icon": "➗",
      "display_order": 40,
      "is_active": true
    },
    {
      "directory_id": "SUB-D-39",
      "kind": "subject_teacher",
      "subject_code": "D",
      "subject_name": "Matematika",
      "person_name": "S. Kurniawan, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "IX",
      "classes": "IX-3, IX-4",
      "icon": "➗",
      "display_order": 40,
      "is_active": true
    },
    {
      "directory_id": "SUB-D-42",
      "kind": "subject_teacher",
      "subject_code": "D",
      "subject_name": "Matematika",
      "person_name": "F. Sahureka, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII, VIII",
      "classes": "VII-5, VIII Bilingual, VIII-1, VIII-5",
      "icon": "➗",
      "display_order": 40,
      "is_active": true
    },
    {
      "directory_id": "SUB-D-43",
      "kind": "subject_teacher",
      "subject_code": "D",
      "subject_name": "Matematika",
      "person_name": "J. Tomatala, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII, VIII",
      "classes": "VII Bilingual, VII Seni, VIII Seni, VIII-2, VIII-3, VIII-4",
      "icon": "➗",
      "display_order": 40,
      "is_active": true
    },
    {
      "directory_id": "SUB-E-02",
      "kind": "subject_teacher",
      "subject_code": "E",
      "subject_name": "IPA",
      "person_name": "L. Reresy, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VIII",
      "classes": "VIII-2, VIII-3, VIII-4",
      "icon": "🔬",
      "display_order": 50,
      "is_active": true
    },
    {
      "directory_id": "SUB-E-05",
      "kind": "subject_teacher",
      "subject_code": "E",
      "subject_name": "IPA",
      "person_name": "J.J Suitela, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "IX",
      "classes": "IX Sains, IX Seni, IX-3",
      "icon": "🔬",
      "display_order": 50,
      "is_active": true
    },
    {
      "directory_id": "SUB-E-06",
      "kind": "subject_teacher",
      "subject_code": "E",
      "subject_name": "IPA",
      "person_name": "E. Bakker, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "IX",
      "classes": "IX Bilingual, IX-2, IX-5",
      "icon": "🔬",
      "display_order": 50,
      "is_active": true
    },
    {
      "directory_id": "SUB-E-07",
      "kind": "subject_teacher",
      "subject_code": "E",
      "subject_name": "IPA",
      "person_name": "M.A Soukotta, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "IX",
      "classes": "IX-2",
      "icon": "🔬",
      "display_order": 50,
      "is_active": true
    },
    {
      "directory_id": "SUB-E-12",
      "kind": "subject_teacher",
      "subject_code": "E",
      "subject_name": "IPA",
      "person_name": "R.Tomagola, S.Pd.,M.MPd",
      "role": "Guru Pengampu",
      "grade_levels": "VII",
      "classes": "VII Bilingual, VII Sains, VII-2",
      "icon": "🔬",
      "display_order": 50,
      "is_active": true
    },
    {
      "directory_id": "SUB-E-16",
      "kind": "subject_teacher",
      "subject_code": "E",
      "subject_name": "IPA",
      "person_name": "Wa Ode Ernawati,S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII, IX",
      "classes": "IX-1, IX-4, VII Seni, VII-1, VII-5",
      "icon": "🔬",
      "display_order": 50,
      "is_active": true
    },
    {
      "directory_id": "SUB-E-23",
      "kind": "subject_teacher",
      "subject_code": "E",
      "subject_name": "IPA",
      "person_name": "J. D. Aliputty, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VIII",
      "classes": "VIII Bilingual, VIII Sains, VIII Seni",
      "icon": "🔬",
      "display_order": 50,
      "is_active": true
    },
    {
      "directory_id": "SUB-E-34",
      "kind": "subject_teacher",
      "subject_code": "E",
      "subject_name": "IPA",
      "person_name": "M. Ririmase, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VIII",
      "classes": "VIII-1, VIII-5",
      "icon": "🔬",
      "display_order": 50,
      "is_active": true
    },
    {
      "directory_id": "SUB-E-41",
      "kind": "subject_teacher",
      "subject_code": "E",
      "subject_name": "IPA",
      "person_name": "M.Saleky, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII",
      "classes": "VII-3",
      "icon": "🔬",
      "display_order": 50,
      "is_active": true
    },
    {
      "directory_id": "SUB-E-44",
      "kind": "subject_teacher",
      "subject_code": "E",
      "subject_name": "IPA",
      "person_name": "M. Leuwol, S.Si",
      "role": "Guru Pengampu",
      "grade_levels": "VII",
      "classes": "VII-4",
      "icon": "🔬",
      "display_order": 50,
      "is_active": true
    },
    {
      "directory_id": "SUB-F-07",
      "kind": "subject_teacher",
      "subject_code": "F",
      "subject_name": "IPS",
      "person_name": "M.A Soukotta, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII, IX",
      "classes": "IX Bilingual, IX-1, IX-4, VII Seni",
      "icon": "🌍",
      "display_order": 60,
      "is_active": true
    },
    {
      "directory_id": "SUB-F-19",
      "kind": "subject_teacher",
      "subject_code": "F",
      "subject_name": "IPS",
      "person_name": "J. Hatu, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VIII, IX",
      "classes": "IX Sains, IX Seni, IX-2, IX-3, IX-5, VIII Seni",
      "icon": "🌍",
      "display_order": 60,
      "is_active": true
    },
    {
      "directory_id": "SUB-F-40",
      "kind": "subject_teacher",
      "subject_code": "F",
      "subject_name": "IPS",
      "person_name": "A. Amarmolo,S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII, VIII",
      "classes": "VII Bilingual, VII Sains, VIII Bilingual, VIII Sains, VIII-2, VIII-5",
      "icon": "🌍",
      "display_order": 60,
      "is_active": true
    },
    {
      "directory_id": "SUB-F-46",
      "kind": "subject_teacher",
      "subject_code": "F",
      "subject_name": "IPS",
      "person_name": "D. D. Fitriany",
      "role": "Guru Pengampu",
      "grade_levels": "VIII",
      "classes": "VIII-1, VIII-3, VIII-4",
      "icon": "🌍",
      "display_order": 60,
      "is_active": true
    },
    {
      "directory_id": "SUB-F-49",
      "kind": "subject_teacher",
      "subject_code": "F",
      "subject_name": "IPS",
      "person_name": "K. Bahy, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII",
      "classes": "VII-1, VII-2, VII-3, VII-4, VII-5",
      "icon": "🌍",
      "display_order": 60,
      "is_active": true
    },
    {
      "directory_id": "SUB-G-03",
      "kind": "subject_teacher",
      "subject_code": "G",
      "subject_name": "Bahasa Inggris",
      "person_name": "M.D.Tuapattinaija, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII, IX",
      "classes": "IX Sains, IX Seni, IX-1, IX-2, IX-3, VII Sains",
      "icon": "🔤",
      "display_order": 70,
      "is_active": true
    },
    {
      "directory_id": "SUB-G-21",
      "kind": "subject_teacher",
      "subject_code": "G",
      "subject_name": "Bahasa Inggris",
      "person_name": "M. Kainama, S.S",
      "role": "Guru Pengampu",
      "grade_levels": "VII, VIII",
      "classes": "VII Seni, VII-3, VII-4, VIII Bilingual, VIII Sains, VIII-5",
      "icon": "🔤",
      "display_order": 70,
      "is_active": true
    },
    {
      "directory_id": "SUB-G-22",
      "kind": "subject_teacher",
      "subject_code": "G",
      "subject_name": "Bahasa Inggris",
      "person_name": "S. Souhoka, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VIII",
      "classes": "VIII Bilingual",
      "icon": "🔤",
      "display_order": 70,
      "is_active": true
    },
    {
      "directory_id": "SUB-G-31",
      "kind": "subject_teacher",
      "subject_code": "G",
      "subject_name": "Bahasa Inggris",
      "person_name": "N. Pranoko, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII, VIII",
      "classes": "VII Bilingual, VIII Seni, VIII-1, VIII-2, VIII-3, VIII-4",
      "icon": "🔤",
      "display_order": 70,
      "is_active": true
    },
    {
      "directory_id": "SUB-G-35",
      "kind": "subject_teacher",
      "subject_code": "G",
      "subject_name": "Bahasa Inggris",
      "person_name": "A. Noya, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII, IX",
      "classes": "IX Bilingual, IX-4, IX-5, VII-1, VII-2, VII-5",
      "icon": "🔤",
      "display_order": 70,
      "is_active": true
    },
    {
      "directory_id": "SUB-H-23",
      "kind": "subject_teacher",
      "subject_code": "H",
      "subject_name": "Seni dan Prakarya",
      "person_name": "J. D. Aliputty, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "IX",
      "classes": "IX Bilingual, IX Sains, IX Seni, IX-1, IX-2, IX-3, IX-4, IX-5",
      "icon": "🎨",
      "display_order": 80,
      "is_active": true
    },
    {
      "directory_id": "SUB-H-41",
      "kind": "subject_teacher",
      "subject_code": "H",
      "subject_name": "Seni dan Prakarya",
      "person_name": "M.Saleky, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VIII",
      "classes": "VIII Seni, VIII-1, VIII-5",
      "icon": "🎨",
      "display_order": 80,
      "is_active": true
    },
    {
      "directory_id": "SUB-H-44",
      "kind": "subject_teacher",
      "subject_code": "H",
      "subject_name": "Seni dan Prakarya",
      "person_name": "M. Leuwol, S.Si",
      "role": "Guru Pengampu",
      "grade_levels": "VII",
      "classes": "VII Bilingual, VII Sains, VII Seni, VII-1, VII-2, VII-3, VII-4, VII-5",
      "icon": "🎨",
      "display_order": 80,
      "is_active": true
    },
    {
      "directory_id": "SUB-H-48",
      "kind": "subject_teacher",
      "subject_code": "H",
      "subject_name": "Seni dan Prakarya",
      "person_name": "A.S.Empo, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VIII",
      "classes": "VIII Sains, VIII-2, VIII-3, VIII-4",
      "icon": "🎨",
      "display_order": 80,
      "is_active": true
    },
    {
      "directory_id": "SUB-I-04",
      "kind": "subject_teacher",
      "subject_code": "I",
      "subject_name": "PJOK",
      "person_name": "E. Wattimena, S.Sos",
      "role": "Guru Pengampu",
      "grade_levels": "IX",
      "classes": "IX Bilingual, IX Sains, IX Seni, IX-1, IX-2, IX-3, IX-4, IX-5",
      "icon": "🏃",
      "display_order": 90,
      "is_active": true
    },
    {
      "directory_id": "SUB-I-27",
      "kind": "subject_teacher",
      "subject_code": "I",
      "subject_name": "PJOK",
      "person_name": "G. Latuheru, S,Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII",
      "classes": "VII Bilingual, VII Sains, VII Seni, VII-1, VII-2, VII-3, VII-4, VII-5",
      "icon": "🏃",
      "display_order": 90,
      "is_active": true
    },
    {
      "directory_id": "SUB-I-29",
      "kind": "subject_teacher",
      "subject_code": "I",
      "subject_name": "PJOK",
      "person_name": "E. Uwaubun, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VIII",
      "classes": "VIII Bilingual, VIII Sains, VIII Seni, VIII-1, VIII-2, VIII-4",
      "icon": "🏃",
      "display_order": 90,
      "is_active": true
    },
    {
      "directory_id": "SUB-J-34",
      "kind": "subject_teacher",
      "subject_code": "J",
      "subject_name": "Informatika",
      "person_name": "M. Ririmase, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "IX",
      "classes": "IX Bilingual, IX Sains, IX Seni, IX-1, IX-2, IX-3, IX-4, IX-5",
      "icon": "💻",
      "display_order": 100,
      "is_active": true
    },
    {
      "directory_id": "SUB-J-45",
      "kind": "subject_teacher",
      "subject_code": "J",
      "subject_name": "Informatika",
      "person_name": "F. Manuhutu, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VIII",
      "classes": "VIII Sains, VIII Seni, VIII-1, VIII-2, VIII-3",
      "icon": "💻",
      "display_order": 100,
      "is_active": true
    },
    {
      "directory_id": "SUB-J-47",
      "kind": "subject_teacher",
      "subject_code": "J",
      "subject_name": "Informatika",
      "person_name": "N.N. Souisa",
      "role": "Guru Pengampu",
      "grade_levels": "VII",
      "classes": "VII Bilingual, VII Sains, VII Seni, VII-1, VII-2, VII-3, VII-4, VII-5",
      "icon": "💻",
      "display_order": 100,
      "is_active": true
    },
    {
      "directory_id": "SUB-J-48",
      "kind": "subject_teacher",
      "subject_code": "J",
      "subject_name": "Informatika",
      "person_name": "A.S.Empo, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII",
      "classes": "VII-4",
      "icon": "💻",
      "display_order": 100,
      "is_active": true
    },
    {
      "directory_id": "SUB-J-50",
      "kind": "subject_teacher",
      "subject_code": "J",
      "subject_name": "Informatika",
      "person_name": "J. G. Wenas, S.Kom",
      "role": "Guru Pengampu",
      "grade_levels": "VIII",
      "classes": "VIII-4, VIII-5",
      "icon": "💻",
      "display_order": 100,
      "is_active": true
    },
    {
      "directory_id": "SUB-K-22",
      "kind": "subject_teacher",
      "subject_code": "K",
      "subject_name": "Bimbingan Konseling",
      "person_name": "S. Souhoka, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "IX",
      "classes": "IX Bilingual, IX Sains, IX Seni, IX-1, IX-2, IX-3, IX-4, IX-5",
      "icon": "🤝",
      "display_order": 110,
      "is_active": true
    },
    {
      "directory_id": "SUB-K-24",
      "kind": "subject_teacher",
      "subject_code": "K",
      "subject_name": "Bimbingan Konseling",
      "person_name": "M. N. Kakiay, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII",
      "classes": "VII Bilingual, VII Sains, VII Seni, VII-1, VII-2, VII-3, VII-4, VII-5",
      "icon": "🤝",
      "display_order": 110,
      "is_active": true
    },
    {
      "directory_id": "SUB-K-32",
      "kind": "subject_teacher",
      "subject_code": "K",
      "subject_name": "Bimbingan Konseling",
      "person_name": "A. Ohello, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VIII",
      "classes": "VIII Bilingual, VIII Sains, VIII Seni, VIII-1, VIII-2, VIII-4, VIII-5",
      "icon": "🤝",
      "display_order": 110,
      "is_active": true
    },
    {
      "directory_id": "SUB-L-39",
      "kind": "subject_teacher",
      "subject_code": "L",
      "subject_name": "Koding / Muatan Lokal",
      "person_name": "S. Kurniawan, S.Pd",
      "role": "Guru Pengampu",
      "grade_levels": "VII",
      "classes": "VII Bilingual, VII Sains, VII Seni, VII-1, VII-3, VII-5",
      "icon": "🧑‍💻",
      "display_order": 120,
      "is_active": true
    }
  ]
};
